spring.application.name=ticket_booking_system

spring.datasource.url= jdbc://postgresql://localhost:8081/Ticket_Management
spring.datasource.username=postgres
spring.datasource.password=Pranathi25
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true